### ISSUE TITLE
Discussion - InvenioRDM @ Northwestern University past approach

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#1]
I kept on putting this off, so I am finally doing it. I am going to outline one of our 'uniquest' permission use case so far and then how we are doing permissions right now with that case as an example and finally how I was originally thinking of moving things forward. I have not looked much at this permissions module so far, so the translation to this module's approach may be trivial (I will attempt to do that exercise in the future).  

**Use case**

We want a librarian role that can be assigned to some users. The librarian can view (read) and edit (update) any bibliographic record that **has been published once**. Whether that record is private or not, or whether that record is really a 'deposit' or a bona fide 'published record', the librarian can access it and modify it. However, if someone has just made a draft of the record and *never* published it, the librarian has no access to it.

**Implementation (for update)**

The logic is in a class dedicated to metadata editing permission. This is the class that is instantiated by the permission factory that is configured to be used for the `update_permission` of the API. 

```python

menrva_edit_published_record = ActionNeed('menrva-edit-published-record')
"""Permission to edit published record ONLY."""

# ...

class EditMetadataPermission(object):
    """Gate to allow or not update of a record metadata.

    We reuse Zenodo's pattern, while trying to simplify it and make it more
    explicit.

    NOTE: It is passed a record (draft OR published).
    NOTE: This is currently used for metadata and files i.e. editing a deposit.
    TODO: Use this just for metadata.
    """

    def __init__(self, user, record):
        """Constructor.

        :param user: typically the current_user.
        :param record: a draft (unpublished record) or published record.
        """
        self.user = user
        self.record = record

    def can(self):
        """Return boolean if permission valid."""
        identity = get_identity(self.user)
        return (
            is_owner(self.user, self.record) or
            (
                # where our use case is implemented
                Permission(menrva_edit_published_record).allows(identity) and
                has_published(self.record)
            ) or
            Permission(menrva_edit).allows(identity)
            # NOTE: by default any Permission has a super-user Need
        )

# search.py
def records_filter():
    """Query ElasticSearch for a *filtered* list of Records.

    NOTE: Any of these queries is run in a filtered context. So ES can
          optimize them.
    """
    if not has_request_context():
        return Q()
    # 'admin-access' is our way to get librarian search access permission
    elif Permission(ActionNeed('admin-access')).can():
        return Q()
    elif not current_user.is_authenticated:
        return (
            Q('term', type='published') &
            Q('term', permissions=RecordPermissions.ALL_VIEW)
        )
    else:
        return (
            Q('term', type='published') &
            (
                Q('term', permissions=RecordPermissions.ALL_VIEW) |
                Q('term', permissions=RecordPermissions.RESTRICTED_VIEW) |
                (
                    Q('term', permissions=RecordPermissions.PRIVATE_VIEW) &
                    Q('term', _deposit__owners=getattr(current_user, 'id', 0))
                )
            )
        )
```

We have a class for creating, viewing (read) too, but we reuse that editing class for the `read_permission` for instance.
 
**Past thought about future**

In terms of how permissions stored on the document in ES/DB, we currently have just visibility stored on the document:

```json
'permissions': '<one of "all_view", "restricted_view", "private_view">'
```

(and even then I didn't put it in the mapping explicitly. I was waiting for the future stuff to come together)

The 'future stuff' was to be something like:

```
'permissions': {
  '<action>': '<user(s) or roles>',
  ...
}
```

The idea would be to then rely on those more explicitly in the search itself.

Hope that is clear and gives you a good idea of what I was thinking of prior to this! Let me know what that makes you think of if anything ;) .

**Comment by lnielsen** [comment]
This is fully supported in the new way and will be quite a lot simpler. It would look something like this:

```python
class LibrariansIfPublished(NeedGenerator):
    def needs(self, record):
        if record['published']:
            return RoleNeed('librarian')

    def query_filter(self):
        if RoleNeed('librarian') in g.identity.provides:
                return Q('term', ...)
        else:
              return Q('term', ...)
        return None
        


class PermissionConfig(...):        
    can_read = [AnyUserIfPublic, Owners, LibrariansIfPublished]
    can_update = [Owners, LibrariansIfPublished]
```

**Comment by fenekku** [comment]
All good with new approach.
