### ISSUE TITLE
Decide on Deny/Empty list of generators and implement: SuperUser+Disable Generators and defaults

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#10]
The meaning/functionality of the `Deny` generator is unclear right now. Should it deny (exclude) ALL users including superusers or should it make an exception for super users?

**Our settled approach**

```python
class MyPolicy(BasePermissionPolicy):
    can_my_action = []
```

is equivalent to 

```python
class MyPolicy(BasePermissionPolicy):
    can_my_action = [SuperUser()]
```

and `SuperUser()` means: allowing super-users.

```python
class MyPolicy(BasePermissionPolicy):
    can_my_action = [Disable()]
```

means no one can perform `my_action` (even super-users). This is needed to enforce usage of Deposits + publish to create records as opposed to creating Records directly. `Deny()` was deemed equivalent to `SuperUser()` so latter is used.

**BLOCKED**: This is blocked on https://github.com/inveniosoftware/invenio-access/pull/166 being accepted so that excludes can be relied on i.e. blocked on #8, #9, #15

**Original discussion**

Given that, should the default list of generators for an action be for example:

```python
can_read = [Deny()]  # for default too
```   

OR

```python
can_read = []  # for default too
```
?

My thoughts are the following:

`Deny` should exclude everyone EXCEPT superuser. A superuser can do **everything**. That is what superuser stands for. I can't imagine a scenario where it shouldn't be able to perform an action (if a person should be *like* a superuser except for some action than that person should have a different role than superuser). This would be (is) baked in the Policy code. Therefore 

```python
can_read = []
```

is fine to only allow superuser read access (even if it was `can_read = [Deny()]` superuser would still be allowed). And because this approach is less wordy, I would recommend it for the default list of generators for an action on `BasePermissionPolicy`.

Thoughts on the matter? @ppanero @lnielsen

**Comment by lnielsen** [comment]
I like the idea of two different generators (with/without superuser granting permission).

Tiny complications to take into account:
- If ``Permission`` class from Flask-Principal is used, it will not allow super user (I hope it's not the case anywhere :-) You have to use Invenio-Access' Permission class to make it work (which you anyway need for actions).

I'll have to think a bit about the naming.

**Comment by ppanero** [comment]
I like the idea. I am just unsure if we need `Deny`. The `Permission` class of `Invenio-Access` [adds super-user](https://github.com/inveniosoftware/invenio-access/blob/master/invenio_access/permissions.py#L112) to the needs by default.

What you mean of `[]` and `Deny` being equivalent is fully true. Then, do we need to implement it? It might be good for "user experience"/"clarity"? If we go for implementing it, we must take into account the excludes prevail over needs.

**Comment by fenekku** [comment]
I see 2 cases for `Deny()` being defined:

1- defined so it can be used in the code for default action (mostly helpful just for us framework developers) so that it *doesn't* have to be explicit for `can_<action>`.
2- defined with constructor taking users / roles, so it can be used to blacklist specific identities. That's useful for hosters / other developers.

The precedence of `excludes` is good for the `Disable()` generator; it allows us to place the `superuser-access` exclude in there (correct?). Other than that, nothing else has to be done (current implementation) to allow superusers but deny everyone else.
