### ISSUE TITLE
Create an AuthenticatedUser generator

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#21]
The `AuthenticatedUser` generator will be useful for only allowing access to signed-in users.

**Comment by lnielsen** [comment]
In principle this should be similar to [AnyUser](https://github.com/inveniosoftware/invenio-records-permissions/blob/master/invenio_records_permissions/generators.py#L45-L59) using the [authenticated_user](https://github.com/inveniosoftware/invenio-access/blob/master/invenio_access/permissions.py#L50) system role.

As for the query, simply duplicate what was done for AnyUser, as we'll have to see during February what is the right thing to do here. It depends on the record's access metadata and it's not final yet.
