### ISSUE TITLE
Implement Access Levels

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#28]
~(Might need an RFC for this)~ RFC: https://github.com/inveniosoftware/rfcs/pull/13

We want access levels to correspond to permissions. Access levels will be a higher-level abstraction over low-level create/read/update/delete... permissions. By being encoded this way on the record's metadata, we can create generators that hold the business logic and are flexible.

**Comment by ppanero** [comment]
I agree, I think an RFC is a good idea for this. Do you think it could fit in the `access control` one? or is too much already?

**Comment by fenekku** [comment]
Yeah, I think an extension to RFC 7 like what I wrote for explicit additional permissions would be best.

**Comment by fenekku** [comment]
Closed via #29
