### ISSUE TITLE
Remove need for running ElasticSearch in tests

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#3]
Tests should be fast and "external software" free i.e. self-contained. Right now, we need a running ElasticSearch container which is not great.

We can place integration tests in the invenio-app-rdm to test with a running instance, perhaps?

**Comment by ppanero** [comment]
Just to point out: This would affect travis not needed to wait for ES :)

**Comment by fenekku** [comment]
Unfortunately, it turns out this module explicitly relies on ElasticSearch (generators' `query`) so we have to use it in tests (and especially multi-versions in Travis). I am closing this for now.
