### ISSUE TITLE
Update Read the Docs to pick up documentation added

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#42]
New documentation is not picked up by the read the docs site. For instance, the Usage section is empty when in fact it is filled out in the repository.

**Comment by lnielsen** [comment]
Update:

The GitHub webhook was correctly configured in RTD, however, the reason why the docs weren't updated was because the docs build failed.

PR #44 should fix the build so that the usage guide should be displayed.
