### ISSUE TITLE
Decouple from invenio-records-rest and invenio-files-rest

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-records-permissions#51]
The new invenio-records-resources and invenio-drafts-resources will totally replace invenio-rest-records and invenio-files-rest (ha naming! :smile: ). This means they replace the endpoints defined in invenio-rest-records and invenio-files-rest. Since invenio-records-permission is importing those 2, the default endpoints are brought along with it. This dependence needs to be severed so that the new endpoints are not overwritten by the old.

It also means integrating permissions with the new repos.

**Comment by ppanero** [comment]
This is mandatory for integration right? As in we cannot integrate resources in RDM without this fixed, because records-rest & co will still be present.

**Comment by fenekku** [comment]
If we want to get permissions integrated this month, then it would be mandatory. I don't know how we are doing permissions-wise: if we think we can achieve permissions integration then great. I can add it for now and we will see if we make it.

**Comment by fenekku** [comment]
We won't be able to achieve this in a while since we are planning on using files-rest for the initial release. Keeping this around, but not assigning it to sprints because it is a longer-term goal.
